from django.contrib.auth import views as auth_views
from django.urls import path
from drf_spectacular.views import SpectacularAPIView

from . import (api, apidocs, bundles, comments, embed, explain, exports, judge, organizer, oversight, participant,
               progress, records, results, tokens, views, voting, webhooks)

urlpatterns = [
    path("", views.gallery),
    path("projects", views.gallery, name="gallery"),
    path("projects/<int:pk>", views.project_page, name="project"),
    path("projects/<int:pk>/comments", comments.post_comment, name="comment-add"),
    path("comments/<int:pk>/moderate", comments.moderate, name="comment-moderate"),
    path("login", views.login_page, name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("signup", views.signup, name="signup"),
    path("me", views.home, name="home"),
    path("me/tokens", tokens.tokens, name="tokens"),
    path("me/tokens/<int:pk>/revoke", tokens.revoke, name="token-revoke"),
    path("events/<slug:slug>/join", participant.join_event, name="event-join"),
    path("events/<slug:slug>/me", participant.event_me, name="event-me"),
    path("events/<slug:slug>/team", participant.create_team, name="team-create"),
    path("events/<slug:slug>/project/new", participant.project_form, name="project-new"),
    path("events/<slug:slug>/project/<int:pk>/edit", participant.project_form, name="project-edit"),
    path("teams/<int:pk>/invites", participant.create_invite, name="invite-create"),
    path("teams/<int:pk>/invites/<int:invite>/revoke", participant.revoke_invite, name="invite-revoke"),
    path("invite/<str:token>", participant.accept_invite, name="invite"),
    path("events/<slug:slug>/vote", voting.ballot, name="ballot"),
    path("events/<slug:slug>/vote/link", voting.request_link, name="vote-link"),
    path("vote/confirm/<str:token>", voting.confirm, name="vote-confirm"),

    path("events/new", organizer.create_event, name="event-new"),
    path("events/<slug:slug>/manage", organizer.manage, name="manage"),
    path("events/<slug:slug>/manage/tracks", organizer.add_track, name="track-add"),
    path("events/<slug:slug>/manage/tracks/<int:pk>/delete", organizer.delete_track, name="track-delete"),
    path("events/<slug:slug>/manage/prizes", organizer.add_prize, name="prize-add"),
    path("events/<slug:slug>/manage/prizes/<int:pk>/delete", organizer.delete_prize, name="prize-delete"),
    path("events/<slug:slug>/manage/rubric", organizer.save_criterion, name="criterion-add"),
    path("events/<slug:slug>/manage/rubric/<int:pk>", organizer.save_criterion, name="criterion-save"),
    path("events/<slug:slug>/manage/rubric/<int:pk>/delete", organizer.delete_criterion, name="criterion-delete"),
    path("events/<slug:slug>/manage/judges/<int:pk>/tracks", organizer.set_judge_tracks, name="judge-tracks"),
    path("events/<slug:slug>/manage/invites", organizer.create_role_invite, name="role-invite"),
    path("events/<slug:slug>/manage/invites/<int:pk>/revoke", organizer.revoke_role_invite, name="role-invite-revoke"),
    path("join/<str:token>", organizer.accept_role_invite, name="role-join"),
    path("events/<slug:slug>/manage/assign", progress.assign, name="assign"),
    path("events/<slug:slug>/manage/assign/manual", progress.assign_manual, name="assign-manual"),
    path("events/<slug:slug>/manage/assign/<int:pk>/delete", progress.unassign, name="unassign"),
    path("events/<slug:slug>/manage/progress", progress.progress, name="progress"),
    path("events/<slug:slug>/manage/calibration", results.calibration_page, name="calibration"),
    path("events/<slug:slug>/manage/publish", results.publish, name="publish"),
    path("events/<slug:slug>/results", results.results_page, name="results"),
    path("events/<slug:slug>/results/<int:pk>", explain.explain_page, name="explain"),
    path("events/<slug:slug>/manage/audit", oversight.audit_page, name="audit"),
    path("events/<slug:slug>/manage/duplicates", oversight.duplicates, name="duplicates"),
    path("events/<slug:slug>/manage/duplicates/<int:pk>", oversight.resolve_duplicate, name="duplicate-resolve"),
    path("events/<slug:slug>/manage/exports", oversight.exports_page, name="exports"),
    path("events/<slug:slug>/manage/voting", voting.voting_page, name="voting-manage"),
    path("events/<slug:slug>/manage/voting/voters/<int:pk>", voting.void_voter, name="voter-void"),

    path("judge", judge.queue, name="judge-queue"),
    path("judge/assignments/<int:pk>", judge.assignment_page, name="judge-assignment"),
    path("judge/assignments/<int:pk>/recuse", judge.recuse, name="judge-recuse"),

    path("api/schema", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/docs", apidocs.api_docs, name="api-docs"),
    path("api/events", api.events, name="api-events"),
    path("api/events/import", bundles.import_bundle_view, name="api-import-bundle"),   # before <slug>
    path("api/events/<slug:slug>", api.event_detail, name="api-event"),
    path("api/events/<slug:slug>/projects", api.event_projects, name="api-event-projects"),
    path("api/events/<slug:slug>/export/<slug:kind>.csv", exports.export_csv, name="api-export"),
    path("api/events/<slug:slug>/results", results.api_results, name="api-results"),
    path("api/events/<slug:slug>/results/signed", results.api_signed_results, name="api-results-signed"),
    path("api/events/<slug:slug>/ballot", voting.api_ballot, name="api-ballot"),
    path("api/projects/<int:pk>", api.project_detail, name="api-project"),
    path("api/projects/<int:pk>/comments", comments.api_comments, name="api-comments"),
    path("api/judge/scores", api.judge_scores, name="api-judge-scores"),
    path("api/judge/assignments", judge.api_assignments, name="api-judge-assignments"),
    path("api/judge/assignments/<int:pk>/review", judge.api_review, name="api-judge-review"),

    # Tier T4: signed records, certificates, the embeddable gallery, event bundles, webhooks.
    path("events/<slug:slug>/certificate", records.certificate, name="certificate"),
    path("verify", records.verify_page, name="verify"),
    path(".well-known/ballotbench-signing-key", records.signing_key, name="signing-key"),
    path("api/verify", records.api_verify, name="api-verify"),
    path("api/judge/record", records.api_judge_record, name="api-judge-record"),
    path("api/participant/record", records.api_participant_record, name="api-participant-record"),
    path("embed/<slug:slug>", embed.embed, name="embed"),
    path("embed.js", embed.embed_js, name="embed-js"),
    path("api/events/<slug:slug>/export/bundle.json", bundles.export_bundle_view, name="api-export-bundle"),
    path("events/<slug:slug>/manage/webhooks", webhooks.webhooks_page, name="webhooks"),
    path("events/<slug:slug>/manage/webhooks/<int:pk>/toggle", webhooks.toggle_webhook, name="webhook-toggle"),
    path("events/<slug:slug>/manage/webhooks/<int:pk>/delete", webhooks.delete_webhook, name="webhook-delete"),
]
