# Generated by Django 5.2.17 on 2026-09-28 04:20

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', portal.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('submissions_open', models.DateTimeField()),
                ('submissions_close', models.DateTimeField()),
                ('judging_open', models.DateTimeField(blank=True, null=True)),
                ('judging_close', models.DateTimeField(blank=True, null=True)),
                ('voting_open', models.DateTimeField(blank=True, null=True)),
                ('voting_close', models.DateTimeField(blank=True, null=True)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
                ('reviews_per_project', models.PositiveSmallIntegerField(default=3)),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('submissions_open__lt', models.F('submissions_close'))), name='event_submission_window'), models.CheckConstraint(condition=models.Q(('judging_open__isnull', True), ('judging_close__isnull', True), ('judging_open__lt', models.F('judging_close')), _connector='OR'), name='event_judging_window'), models.CheckConstraint(condition=models.Q(('voting_open__isnull', True), ('voting_close__isnull', True), ('voting_open__lt', models.F('voting_close')), _connector='OR'), name='event_voting_window'), models.CheckConstraint(condition=models.Q(('reviews_per_project__gte', 1)), name='event_k_positive'), models.CheckConstraint(condition=models.Q(('max_team_size__gte', 1)), name='event_team_size_positive')],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('input_digest', models.CharField(max_length=64)),
                ('connected', models.BooleanField()),
                ('notes', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_runs', to='portal.event')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('row_hash', models.CharField(blank=True, max_length=64)),
                ('seq', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.event')),
            ],
            options={
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='JudgeCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_reviews', models.PositiveSmallIntegerField()),
                ('offset', models.FloatField()),
                ('scale', models.FloatField()),
                ('noise', models.FloatField()),
                ('flag', models.CharField(choices=[('ok', 'Ok'), ('constant', 'Constant'), ('single_review', 'Single Review')], max_length=20)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='portal.calibrationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True, max_length=500)),
                ('demo_url', models.URLField(blank=True, max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='portal.project')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.event')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('recused', 'Recused')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.project')),
            ],
        ),
        migrations.CreateModel(
            name='CalibratedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_reviews', models.PositiveSmallIntegerField()),
                ('raw_mean', models.FloatField()),
                ('quality', models.FloatField()),
                ('display', models.FloatField()),
                ('se', models.FloatField()),
                ('rank', models.PositiveIntegerField(null=True)),
                ('raw_rank', models.PositiveIntegerField(null=True)),
                ('excluded', models.CharField(blank=True, max_length=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.calibrationrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='portal.judgeassignment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('min_value', models.SmallIntegerField(default=1)),
                ('max_value', models.SmallIntegerField(default=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='portal.event')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.rubriccriterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='portal.review')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='portal.event')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.team'),
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='portal.team')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='portal.event')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.track'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='portal.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.track')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portal.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(blank=True, to='portal.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='user_email_lowercase'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event', 'action'], name='portal_audi_event_i_344b31_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgecalibration',
            constraint=models.UniqueConstraint(fields=('run', 'judge'), name='judge_calibration_unique'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['event', 'judge'], name='portal_judg_event_i_800362_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='calibratedproject',
            constraint=models.UniqueConstraint(fields=('run', 'project'), name='calibrated_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='criterion_key_per_event'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='criterion_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('min_value__lt', models.F('max_value'))), name='criterion_range'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='score_unique'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='team_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'external_id'), name='team_external_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.CheckConstraint(condition=models.Q(('used_by__isnull', True), ('used_at__isnull', False), _connector='OR'), name='invite_used_has_time'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='one_team_per_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='track_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'external_id'), name='track_external_id_per_event'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['event', 'status'], name='portal_proj_event_i_fb6e8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('event', 'external_id'), name='project_external_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), ('submitted_at__isnull', False)), models.Q(('status', 'draft'), ('submitted_at__isnull', True)), _connector='OR'), name='project_submitted_has_time'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('duplicate_of', models.F('pk')), _negated=True), name='project_not_own_duplicate'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='prize_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'role'), name='membership_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('event', 'role', 'external_id'), name='membership_external_id'),
        ),
    ]
