# Generated by Django 5.2.17 on 2026-09-28 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_audit_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portal.rubriccriterion'),
        ),
    ]
