# Generated by Django 5.2.17 on 2026-09-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_score_criterion_restrict'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='team_name_per_event',
        ),
    ]
