# Generated by Django 5.2.17 on 2026-09-28 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_team_names_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('judge', 'judge'), ('organizer', 'organizer')], max_length=20)),
                ('note', models.CharField(blank=True, help_text='who it is for, for your own records', max_length=200)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_invites', to='portal.event')),
                ('tracks', models.ManyToManyField(blank=True, to='portal.track')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('used_by__isnull', True), ('used_at__isnull', False), _connector='OR'), name='role_invite_used_has_time')],
            },
        ),
    ]
