# Generated by Django 5.2.17 on 2026-09-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_role_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='notes',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='converged',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='n_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='signal_p',
            field=models.FloatField(help_text='permutation p-value: do judges agree more than chance?', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='portal.calibrationrun'),
        ),
    ]
