# Generated by Django 5.2.17 on 2026-09-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_published_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratedproject',
            name='rank_high',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calibratedproject',
            name='rank_low',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
