# Generated by Django 5.2.17 on 2026-09-28 05:14

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_vote_rules'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 2000), name='comment_max_length'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.CheckConstraint(condition=models.Q(('voided_at__isnull', True), models.Q(('voided_reason', ''), _negated=True), _connector='OR'), name='voter_void_has_reason'),
        ),
    ]
