# Generated by Django 5.2.17 on 2026-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duplicate_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
