# Generated by Django 5.2.17 on 2026-09-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_duplicate_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
